import Lab1 from "./labs1";
import Lab2 from "./labs2";
import Lab3 from "./labs3";
import Lab4 from "./labs4";
import Lab5 from "./labs5";
import Lab6 from "./labs6";
import Lab7 from "./labs7";
import Lab8 from "./labs8";
import Lab9 from "./labs9";
import Lab10 from "./labs10";
export { Lab1, Lab2, Lab3, Lab4, Lab5, Lab6, Lab7, Lab8, Lab9, Lab10 };
